name: fresher
description: >-
  A tool to help keep your multiple projects in multiple repositories up to date:
  automated upgrade dependencies, update links, files, etc.
repository: https://github.com/signmotion/fresher
topics:
  - tools
  - maintenance
  - automated
  - git
  - template

# Compatible with https://semver.org
# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.1.5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.5.0
  chalkdart: ^2.2.1
  cli_table: ^1.0.2
  collection: ">=1.18.0 <3.0.0"
  emoji_regex: ^0.0.5
  equatable: ^2.0.5
  json_dart: ^0.1.4
  logger: ^2.4.0
  meta: ">=1.10.0 <3.0.0"
  mustache_template: ^2.0.0
  path: ">=1.7.0 <3.0.0"
  process: ">=4.2.4 <6.0.0"
  pub_semver: ^2.1.4
  pub_updater: ^0.5.0
  recase: ^4.1.0
  wfile: ^0.5.3
  yaml: ^3.1.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  test_process: ^2.1.0

screenshots:
  - description: "Fresher demo"
    path: images/screenshots/log_output_example.webp
